channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=25.1
- pip:
  - mlflow==2.16.2
  - cloudpickle==3.1.1
  - numpy==1.26.3
  - pandas==2.2.0
  - torch==2.2.0
  - tqdm==4.67.1
name: mlflow-env
